### ISSUE TITLE
TokenMismatchException Hatası

### ISSUE THREAD

**Issue by ZgrK** [cuneydtural/smartpanel#2]
Kurulumu sayfadaki gibi yaptıktan sonra login olmaya çalışınca aşağıdaki hatayı çıkartıyor. 
<img width="1037" alt="screen shot 2016-12-10 at 3 52 11 am" src="https://cloud.githubusercontent.com/assets/879674/21070338/257e289c-be8c-11e6-85cf-aa42d16bc7be.png">

**Comment by cuneydtural** [comment]
`php artisan cache:clear` komutunu deneyebilir misin ?

**Comment by ZgrK** [comment]
denedim yine aynı sorun var direk bir ubuntu sunucuya kurdum bunu ben domainle http://otto.zgrkaralar.com/ test edebilirsiniz

**Comment by cuneydtural** [comment]
`views/auth/login.blade.php` içerisinde `{!! csrf_field() !!}` yerine `<input type="hidden" name="_token" value="{{ csrf_token() }}">` şeklinde deneyebilir misiniz ?

**Comment by cuneydtural** [comment]
PHP MCrypt eklentisini de kontrol edebilir misiniz ?

**Comment by ZgrK** [comment]
Malesef devam ediyor hata

**Comment by cuneydtural** [comment]
Bugün iki farklı sunucuya test kurulumu yaptık. Herhangi bir problem yok. Kurulum adımlarını tekrar kontrol edebilir misiniz ?
